version: "3.1"
assistant_id: "travel chatbot"
language: "en"

pipeline:
  # order is important!
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  # - name: "FallbackClassifier"
  #   threshold: 0.1

policies:
  - name: RulePolicy
    # core_fallback_action_name: "action_default_fallback"
    # core_fallback_threshold: 0.2
    # enable_fallback_prediction: true
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
  # - name: "UnexpecTEDIntentPolicy"
  #   epochs: 50
